name: IOS Build

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/ios.yml"
      - "**.js"
      - "**.json"
      - "**.ts"
      - "**.tsx"
      - "template/.eslint*"
      - "template/.prettier*"
      - "template/package.json"
      - "template/tsconfig.json"
      - "template/yarn.lock"
      - "template/ios/**"
      - "template/.bundle/**"
      - "template/.ruby-version"
      - "template/Gemfile"
      - "template/Gemfile.lock"
      - "template/Gemfile"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/ios.yml"
      - "**.js"
      - "**.json"
      - "**.ts"
      - "**.tsx"
      - "template/package.json"
      - "template/yarn.lock"
      - "template/ios/**"
      - "template/.bundle/**"
      - "template/.ruby-version"
      - "template/Gemfile"
      - "template/Gemfile.lock"
      - "template/Gemfile"
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ios-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ios:
    name: IOS Build
    runs-on: macOS-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: template
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: "template/.nvmrc"
          cache: "yarn"
          cache-dependency-path: template/yarn.lock
      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: template
      - name: Install dependencies
        run: yarn
      - name: Pods cache
        uses: actions/cache@v2
        with:
          path: |
            template/ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('template/ios/Podfile.lock') }}
      - name: Install Pods
        run: cd ios && pod install --repo-update && cd ..
      - name: Missing Simulator Executable Workaround
        # See https://github.com/actions/virtual-environments/issues/4545#issuecomment-975719151
        run: /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/Xcode_13.2.1.app/Contents/Developer/Applications/Simulator.app
      - name: IOS Release Build
        run: yarn ios --configuration Release
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: HelloWorld.app
          path: /Users/runner/Library/Developer/Xcode/DerivedData/HelloWorld-*/Build/Products/Release-iphonesimulator/HelloWorld.app
